#!/bin/sh

#SBATCH --job-name=ds000223-mriqc
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000223-mriqc/.reproman/jobs/local/20220811-140929-f9c5/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000223-mriqc/.reproman/jobs/local/20220811-140929-f9c5/stderr

#SBATCH --nodes=4
#SBATCH --ntasks=19
#SBATCH --time=8:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000223-mriqc/.reproman/jobs/local/20220811-140929-f9c5

module load launcher
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 18); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

"$LAUNCHER_DIR"/paramrun